before_script:
    - apt-get install golang

stages:
    - test
    - run

test:
    stage: test
    script:
        - go test


run:
    stage: run
    script:
        - go run main.go
    environment: test


