image: ubuntu:14.04

before_script:
    - apt-get update
    - apt-get install -y golang

stages:
    - test
    - run

test:
    stage: test
    script:
        - go test


run:
    stage: run
    script:
        - go run main.go
    environment: test


